import react from 'react';

export default {
  map_title: 'The Path Forward',
  map_content: 'Isolated we are all each but an island. Together, we shine. It’s more than a game.',

  map_item1_number: '01',
  map_item1_name: 'Vision',
  map_item1_InfoTitle: 'Vision',
  map_item1_InfoContent1: 'I logged in 14C. I saw 14,000,605 futures.',
  map_item1_InfoContent2: 'We do not define 14C just as a “game”. It is rather a wormhole between the physical reality and the plausible simulations of our future – one where resources are depleted, and humanity is tested.',
  map_item1_InfoContent3: 'If Sci-Fi could be a crystal ball, so is our game. History and recent trends shows how we slip into mania and despair faster and deeper than reason can anticipate...',
  map_item1_InfoContent4: 'How would you act for a change?',
  map_item1_InfoContent5: 'We gather here for leisure gateways and more. We communicate, observe and learn from each other.We go influence the physical world.',

  map_item2_number: '02',
  map_item2_name: 'Game Assets',
  map_item2_InfoTitle: 'Game Assets',
  map_item2_InfoContent1: 'PFP NFT- Launching End of June; Join Discord to learn more!',
  map_item2_InfoContent2: 'A PFP (profile picture) non-fungible token (NFT) is a unique digital asset that represents ownership of your character in the 14C world. Hodlers will be entitled to the below benefits:',
  map_item2_InfoContent2_benefit_1: 'White paper publishing - 22Q2',
  map_item2_InfoContent2_benefit_2: 'Monthly balance update',
  map_item2_InfoContent2_benefit_3: 'Internal alpha testing – 22Q3',
  map_item2_InfoContent2_benefit_4: 'Game launch – 22Q4',
  map_item2_InfoContent3: 'Land - Coming soon!',
  map_item2_InfoContent3_1: 'Land is the<b>core resource</b> of the 14C world.This is where resources are mined, cities are built, and legendary friendships are formed.',
  map_item2_InfoContent3_2: 'Because 14C is based on a post-climate disaster apocalypse, we want to utilize our lands to mirror the lands in physical reality. Owners of the 14C land may collect rents as we bring in <b> brands and merchandise</b> to situate in the 14C dystopia.',
  map_item2_InfoContent3_3: 'We may also experiment to <b> digitalize physical natural resources</b> into 14C <b>Limited Center City</b>, projecting the natural resource reserve on-chain. Guilds and leagues will compete to take ownership of the Limited Center City.',
  map_item2_InfoContent4: 'Token - Coming soon!',
  map_item2_InfoContent4_1: 'Our token will be the <b>official currency</b> to use in the game for training and recruiting your troops, contributing to your guild, and participating in exciting prediction mini-games & league events.',
  map_item2_InfoContent4_2: 'In addition, we may explore adopting a green data center for our game server, so as to <b>airdrop carbon credits</b> as side benefits.',
  map_item2_InfoContent4_3: 'We also value guilds as the foundation of the 14C world. We hope to assist the rising 14-native, <b>rising MVP guilds</b> to issue their <b>fans token</b> guilds to grow and benefit their fans. Break the limits.',
  map_item2_InfoContent5: 'Champions - Coming soon!',
  map_item2_InfoContent5_1: 'Champions, with <b>various buffs and rarity</b>, are key to helping you mine resources, build cities, and fight against foes. We may also explore <b> limited-edition crossover suits & skins </b> to celebrate special moments in 14C world,or to collaborate with tech gadgets to link up your <b>physical efforts to your champion upgrades</b>.',
  map_item2_InfoContent6: '14C is a lab. We aim to restlessly invent and try innovative features.Join us to brainstorm, design, and build together!',


  map_item3_number: '03',
  map_item3_name: 'Gameplay',
  map_item3_InfoTitle: 'Gameplay',
  map_item3_InfoContent1: 'Satellite City - Shimmer’s Home Base',
  map_item3_InfoContent1_1: '<b>Construction</b>: Shimmers can develop their Satellite Cities by building and upgrading Facilities',
  map_item3_InfoContent1_2: '<b>Production</b>: Facilities in Satellite Cities provide a constant source of resource production',
  map_item3_InfoContent1_3: '<b>Research</b>: Research enhances battle abilities and production efficiency',
  map_item3_InfoContent1_4: '<b>Recruitment</b>: Summon Champions and Guards to form Troops；use Troops to to defend against invasions and to march into the Cosmos for hunting and battling',
  map_item3_InfoContent2: 'Cosmos - the Open-World Map',
  map_item3_InfoContent2_1: '<b>Solo</b>: Collecting resources among the scattered resource points',
  map_item3_InfoContent2_2: '<b>Solo/PvE</b>: Battling with Crazed/Weirdlings for resources and level up',
  map_item3_InfoContent2_3: '<b>PvP</b>: Raiding fellow Shimmers',
  map_item3_InfoContent2_4: '<b>GvG</b>: Battling among Alliances to conquer the 14C world',


  map_item4_number: '04',
  map_item4_name: 'Roadmap',
  map_item4_InfoTitle: 'Roadmap',
  map_item4_InfoContent1: '22Q1',
  map_item4_InfoContent1_1: 'Convene team - Check!',
  map_item4_InfoContent1_2: 'Website and community set up - Check!',
  map_item4_InfoContent1_3: 'Game internal testing - Check!',
  map_item4_InfoContent2: '22Q2',
  map_item4_InfoContent2_1: 'Issue <b>PFP NFT</b>',
  map_item4_InfoContent2_2: 'Expand <b>PFP NFT</b> to external secondary marketplaces',
  map_item4_InfoContent2_3: 'Open 14C Club',
  map_item4_InfoContent2_4: 'Refine tokenomics',
  map_item4_InfoContent2_5: 'Disclose funding usage',
  map_item4_InfoContent3: '22Q3',
  map_item4_InfoContent3_1: 'Issue <b>Land NFT</b>',

  map_item4_InfoContent3_2: 'Launch <b>14C Official Marketplace</b> for game assets',
  map_item4_InfoContent3_3: 'Launch game alpha testing',
  map_item4_InfoContent3_4: 'Start 14C grants for co-creation work',
  map_item4_InfoContent4: '22Q4',
  map_item4_InfoContent4_1: 'Issue <b>Token Sale</b>',
  map_item4_InfoContent4_2: 'List Token to external secondary marketplaces',
  map_item4_InfoContent4_3: 'Enable Token staking',
  map_item4_InfoContent4_4: 'Launch game',
  map_item4_InfoContent4_5: 'Onboard guilds and prepare for S1 League',


  map_item5_number: '05',
  map_item5_name: 'Join the Team',
  map_item5_InfoTitle: 'Join the Team',
  map_item5_InfoContent1: '(Full time / Part time) Looking for community leaders to assist managing our growing community of passionate humans revolutionizing how game creates value.',
  map_item5_InfoContent2: 'This is a highly visible role with our user base and the broader ecosystem.',
  map_item5_InfoContent3: 'You will:',
  map_item5_InfoContent4: 'Lead community initiatives to educate and grow our larger user base and key audiences.',
  map_item5_InfoContent5: 'Engage with 14C’s community in a meaningful way by responding to customer questions, managing support requests, hosting office hour calls, and leading fun community engagement programs via Discord and Twitter.',
  map_item5_InfoContent6: 'Work cross-functionally with customer, partnerships, and legal teams to turn community engagement into active game development opportunities.',
  map_item5_InfoContent7: 'Requirements:',
  map_item5_InfoContent8: 'Deeply passionate about game and crypto with a strong understanding of the community behaviors.',
  map_item5_InfoContent9: 'Self starter and can work effectively in a fast-paced remote environment with flexible working hours',
  map_item5_InfoContent10: 'Nice to have prior experience contributing to GameFi or other DAO communities',
  map_item5_InfoContent11: 'Contact us in Twitter & Discord',
}