export default {
  map_title: 'The Path Forward',
  map_content: 'Isolated we are all each but an island. Together, we shine. It’s more than a game.',

  map_item1_number: '01',
  map_item1_name: 'Vision',
  map_item1_InfoTitle: 'Vision',
  map_item1_InfoContent1: 'I logged in 14C. I saw 14,000,605 futures.',
  map_item1_InfoContent2: 'We do not define 14C just as a “game”. It is rather a wormhole between the physical reality and the plausible simulations of our future – one where resources are depleted, and humanity is tested.',
  map_item1_InfoContent3: 'If Sci-Fi could be a crystal ball, so is our game. History and recent trends shows how we slip into mania and despair faster and deeper than reason can anticipate...',
  map_item1_InfoContent4: 'How would you act for a change?',
  map_item1_InfoContent5: 'We gather here for leisure gateways and more. We communicate, observe and learn from each other.We go influence the physical world.',

  map_item2_number: '02',
  map_item2_name: 'Game Development',
  map_item2_InfoTitle: 'Game Development',
  map_item2_InfoContent1: '· White paper publishing - 22Q2',
  map_item2_InfoContent2: '· Monthly balance update',
  map_item2_InfoContent3: '· Internal alpha testing – 22Q3',
  map_item2_InfoContent4: '· Game launch – 22Q4',

  map_item3_number: '03',
  map_item3_name: 'Community',
  map_item3_InfoTitle: 'Community',
  map_item3_InfoContent1: '· Onboard guilds and prepare for S1 League – starts in 22Q2',
  map_item3_InfoContent2: 'We welcome existing guilds and newly formed alliances to battle at the League. Even just as members of the audience, gamers can enjoy analyzing and predicting the battles. The more community engaged the merrier.',
  map_item3_InfoContent3: '· Establish productive DAO – 22Q3',
  map_item3_InfoContent4: 'We are gamers but also thinkers and Web3 builders. Speak out your view on new labor structure, show your study on sustainability, or brainstorm mini green energy systems together.',
  map_item3_InfoContent5: '· 14C Grants – 23Q1',
  map_item3_InfoContent6: 'We call for developers, creators and artists to co-build 14C characters, maps, exchanges and even another game.',

  map_item4_number: '04',
  map_item4_name: 'Fork Reality',
  map_item4_InfoTitle: 'Fork Reality: Sustainability',
  map_item4_InfoContent1: '· Digitalize physical resources',
  map_item4_InfoContent2: 'We transform the real-world zones - from forests to gold mines - into 14C as Limited Reserve Map. As our real-world partners make a pledge to reduce resources consumption, we project the reserve on-chain. Guilds and leagues will compete to take ownership of the Limited Reserve Map in the form of NFT, and individual member of the guilds will own fractional NFT to demonstrate contributions and collectively decide how to deal with the resources.',
  map_item4_InfoContent3: '· Use green data centre and airdrop carbon credits',
  map_item4_InfoContent4: 'Our server will seek to be deployed in data centres (IDC) powered by renewable energy (hydro, wind, solar) In the case that IDC produces negative-carbon, we will also collect and airdrop carbon credits. Gamers can use for offset or for trades.',
  map_item4_InfoContent5: '· Cross-over with physical gadgets',
  map_item4_InfoContent6: 'Blurring the edge of reality and 14C. Which one is real anyway? We plan to collaborate with tech gadgets so to link up your physical behaviors to your Shimmer. Act for a change.',

  map_item5_number: '05',
  map_item5_name: 'Community Leader',
  map_item5_InfoTitle: 'Community Leader',
  map_item5_InfoContent1: '(Full time / Part time) Looking for community leaders to assist managing our growing community of passionate humans revolutionizing how game creates value.',
  map_item5_InfoContent2: 'This is a highly visible role with our user base and the broader ecosystem.',
  map_item5_InfoContent3: 'You will:',
  map_item5_InfoContent4: '* Lead community initiatives to educate and grow our larger user base and key audiences.',
  map_item5_InfoContent5: '* Engage with 14C’s community in a meaningful way by responding to customer questions, managing support requests, hosting office hour calls, and leading fun community engagement programs via Discord and Twitter.',
  map_item5_InfoContent6: '* Work cross-functionally with customer, partnerships, and legal teams to turn community engagement into active game development opportunities.',
  map_item5_InfoContent7: 'Requirements:',
  map_item5_InfoContent8: '* Deeply passionate about game and crypto with a strong understanding of the community behaviors.',
  map_item5_InfoContent9: '* Self starter and can work effectively in a fast-paced remote environment with flexible working hours',
  map_item5_InfoContent10: '* Nice to have prior experience contributing to GameFi or other DAO communities',
  map_item5_InfoContent11: 'Contact us in Twitter & Discord',
}